HdlTopicNewDataMissing: TopicNew data is corrupted or missing
HdlTopicViewParameterCorrupt: TopicView parameter is corrupted
HdlTopicModDataMissing: TopicMod data is corrupted or missing
HdlTopicViewUnauthorized: TopicView unauthorized
HdlTopicModUnauthorized: TopicMod unauthorized
HdlArticleNewDataMissing: ArticleNew data is corrupted or missing
HdlArticleViewUnauthorized: ArticleView unauthorized
HdlArticleModDataMissing: ArticleMod data is corrupted or missing
HdlArticleModUnauthorized: ArticleMod unauthorized
HdlArticleMoveParameterMissing: AriticleMove parameter is missing
HdlParagraphModDataMissing: ParagraphMod data is corrupted or missing
HdlParagraphNewDataMissing: ParagraphNew data is corrupted or missing
HdlParagraphMovDataMissing: ParagraphMov data is corrupted or missing
HdlArticleNotExist: Requested article does not exist
HdlParagraphNotExist: Requested paragraph does not exist
HdlParagraphLocked: Requested paragraph is locked and cannot be edited
HdlCompareParagraphsFromDifferentArticle: Cannot compare two paragraphs from different articles
ArticleListEmpty: There are currently no articles yet. You may initiate a new one
NotImplemented: The functionality has not yet been implemented
