Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://192.168.56.101:3000"
  copyright: Recursive Copyleft. Powered by Yesod.
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
